SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';


-- -----------------------------------------------------
-- TABLE `bocai`.`BC_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_USER` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_USER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(45) NULL ,
  `FIRST_EMAIL` VARCHAR(45) NOT NULL ,
  `SECONDARY_EMAIL` VARCHAR(45) NULL ,
  `PASSWORD` VARCHAR(45) NULL ,
  `SIGNATURE` VARCHAR(100) NULL ,
  `CITY_NAME` VARCHAR(45) NULL ,
  `BIRTHDAY` DATE NULL ,
  `MSN` VARCHAR(45) NULL ,
  `QQ` VARCHAR(45) NULL ,
  `BLOG_URL` VARCHAR(100) NULL ,
  `SEXY` INT NULL,
  `AGE` INT NULL,
  `WEIGHT` INT NULL ,
  `HEIGHT` INT NULL ,
  `FOLLOWED_BY_NUM` INT NULL DEFAULT 0 ,
  `FOLLOW_TO_NUM` INT NULL DEFAULT 0 ,
  `ADDRESS` VARCHAR(100) NULL ,
  `PHONE_NO` VARCHAR(45) NULL ,
  `STAUTS` INT NOT NULL DEFAULT 0 ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) )
ENGINE = INNODB;

-- -----------------------------------------------------
-- TABLE `bocai`.`BC_USER_PHOTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_USER_PHOTO` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_USER_PHOTO` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `PATH` VARCHAR(100) NULL ,
  `USER_ID` BIGINT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_USER_PHOTO_USER1` (`USER_ID` ASC) ,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) ,
  CONSTRAINT `FK_USER_PHOTO_USER1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;

-- -----------------------------------------------------
-- TABLE `bocai`.`BC_POST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_POST` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_POST` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `TITLE` VARCHAR(45) NULL ,
  `CONTENT` VARCHAR(1000) NULL ,
  `STATUS` INT NOT NULL DEFAULT 0 ,
  `POST_BY` VARCHAR(45) NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `CREATED_AT` DATE NOT NULL ,
  `UPDATED_BY` BIGINT NULL ,
  `UPDATED_AT` DATE NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_POST_USER1` (`CREATED_BY` ASC) ,
  INDEX `FK_POST_USER2` (`UPDATED_BY` ASC) ,
  CONSTRAINT `FK_POST_USER1`
    FOREIGN KEY (`CREATED_BY` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION ,
  CONSTRAINT `FK_POST_USER2`
    FOREIGN KEY (`UPDATED_BY` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;

-- -----------------------------------------------------
-- TABLE `bocai`.`BC_COMMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_COMMENT` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_COMMENT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `CONTENT` VARCHAR(600) NULL ,
  `STATUS` INT NULL ,
  `GOOD_COUNT` INT NULL ,
  `GREAT_COUNT` INT NULL ,
  `POST_ID` BIGINT NOT NULL ,
  `COMMENT_BY` BIGINT NOT NULL ,
  `COMMENT_AT` DATE NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_COMMENTS_USER1` (`COMMENT_BY` ASC) ,
  INDEX `FK_COMMENTS_POST1` (`POST_ID` ASC) ,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) ,
  CONSTRAINT `FK_COMMENTS_USER1`
    FOREIGN KEY (`COMMENT_BY` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMMENTS_POST1`
    FOREIGN KEY (`POST_ID` )
    REFERENCES `bocai`.`BC_POST` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;

-- -----------------------------------------------------
-- TABLE `bocai`.`BC_THIRDPARTY_ACCOUNT_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_THIRDPARTY_ACCOUNT_TYPE` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_THIRDPARTY_ACCOUNT_TYPE` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `ACCOUNT_TYPE` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) )
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `bocai`.`BC_USER_THIRDPARTY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_USER_THIRDPARTY` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_USER_THIRDPARTY` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `ACCOUNT` VARCHAR(45) NOT NULL ,
  `PASSWORD` VARCHAR(45) NULL ,
  `URL` VARCHAR(45) NULL ,
  `USER_ID` BIGINT NOT NULL ,
  `ACCOUT_TYPE_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_USER_THIRDPARTY_USER` (`USER_ID` ASC) ,
  INDEX `FK_USER_THIRDPARTY_THIRDPARTY_DEFINITION1` (`ACCOUT_TYPE_ID` ASC) ,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) ,
  CONSTRAINT `FK_USER_THIRDPARTY_USER`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USER_THIRDPARTY_THIRDPARTY_DEFINITION1`
    FOREIGN KEY (`ACCOUT_TYPE_ID` )
    REFERENCES `bocai`.`BC_THIRDPARTY_ACCOUNT_TYPE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;








-- -----------------------------------------------------
-- TABLE `bocai`.`BC_PLACE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_PLACE` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_PLACE` (
  `ID` BIGINT NOT NULL ,
  `NAME` VARCHAR(100) NULL ,
  `LOCATION` VARCHAR(100) NULL ,
  `ADDRESS` VARCHAR(200) NULL ,
  `LINKS` VARCHAR(100) NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) )
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `bocai`.`BC_DISH`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_DISH` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_DISH` (
  `POST_ID` BIGINT NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  `PRICE` VARCHAR(45) NULL ,
  `DESCRIPTION` VARCHAR(600) NULL ,
  `TASTED_NUM` INT NULL DEFAULT 0 ,
  `WANTED_NUM` INT NULL DEFAULT 0 ,
  `GRADE` VARCHAR(45) NULL ,
  `STATUS` VARCHAR(45) NULL ,
  `SPOTTED_TIMES` INT NULL DEFAULT 0 ,
  `SHARED_TIMES` INT NULL DEFAULT 0 ,
  `VIEWED_TIMES` INT NULL DEFAULT 0 ,
  `LINKS` VARCHAR(200) NULL ,
  `BEST_PHOTO_FROM` VARCHAR(45) NULL ,
  `PLACE_ID` BIGINT NOT NULL ,
  PRIMARY KEY (`POST_ID`) ,
  INDEX `FK_DISH_PLACE1` (`PLACE_ID` ASC) ,
  CONSTRAINT `FK_DISH_POST1`
    FOREIGN KEY (`POST_ID` )
    REFERENCES `bocai`.`BC_POST` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DISH_PLACE1`
    FOREIGN KEY (`PLACE_ID` )
    REFERENCES `bocai`.`BC_PLACE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `bocai`.`BC_DISH_TAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_DISH_TAG` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_DISH_TAG` (
  `ID` INT NOT NULL ,
  `TAG_NAME` VARCHAR(100) NULL ,
  `DISH_ID` BIGINT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) ,
  INDEX `FK_BC_DISH_TAGS_BC_DISHS1` (`DISH_ID` ASC) ,
  CONSTRAINT `FK_BC_DISH_TAGS_BC_DISHS1`
    FOREIGN KEY (`DISH_ID` )
    REFERENCES `bocai`.`BC_DISH` (`POST_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `bocai`.`BC_DISH_PHOTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_DISH_PHOTO` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_DISH_PHOTO` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `PATH` VARCHAR(45) NULL ,
  `DISH_ID` BIGINT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_BC_DISH_PHOTOS_BC_DISHS1` (`DISH_ID` ASC) ,
  CONSTRAINT `FK_BC_DISH_PHOTOS_BC_DISHS1`
    FOREIGN KEY (`DISH_ID` )
    REFERENCES `bocai`.`BC_DISH` (`POST_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;





-- -----------------------------------------------------
-- TABLE `bocai`.`BC_USER_FOLLOWSHIP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_USER_FOLLOWSHIP` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_USER_FOLLOWSHIP` (
  `USER_ID` BIGINT NOT NULL ,
  `USER_ID_TO` BIGINT NOT NULL ,
  `FOLLOW_AT` VARCHAR(45) NULL ,
  PRIMARY KEY (`USER_ID`, `USER_ID_TO`) ,
  INDEX `FK_USER_HAS_USER_USER2` (`USER_ID_TO` ASC) ,
  INDEX `FK_USER_HAS_USER_USER1` (`USER_ID` ASC) ,
  CONSTRAINT `FK_USER_HAS_USER_USER1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USER_HAS_USER_USER2`
    FOREIGN KEY (`USER_ID_TO` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `bocai`.`BC_XREF_USER_DISH_TASTED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_XREF_USER_DISH_TASTED` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_XREF_USER_DISH_TASTED` (
  `USER_ID` BIGINT NOT NULL ,
  `DISH_ID` BIGINT NOT NULL ,
  PRIMARY KEY (`USER_ID`, `DISH_ID`) ,
  INDEX `FK_BC_USERS_HAS_BC_DISHS_BC_DISHS1` (`DISH_ID` ASC) ,
  INDEX `FK_BC_USERS_HAS_BC_DISHS_BC_USERS1` (`USER_ID` ASC) ,
  CONSTRAINT `FK_BC_USERS_HAS_BC_DISHS_BC_USERS1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BC_USERS_HAS_BC_DISHS_BC_DISHS1`
    FOREIGN KEY (`DISH_ID` )
    REFERENCES `bocai`.`BC_DISH` (`POST_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `bocai`.`BC_XREF_USER_DISH_WANTED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_XREF_USER_DISH_WANTED` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_XREF_USER_DISH_WANTED` (
  `USER_ID` BIGINT NOT NULL ,
  `DISH_ID` BIGINT NOT NULL ,
  PRIMARY KEY (`USER_ID`, `DISH_ID`) ,
  INDEX `FK_BC_USERS_HAS_BC_DISHS_BC_DISHS2` (`DISH_ID` ASC) ,
  INDEX `FK_BC_USERS_HAS_BC_DISHS_BC_USERS2` (`USER_ID` ASC) ,
  CONSTRAINT `FK_BC_USERS_HAS_BC_DISHS_BC_USERS2`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BC_USERS_HAS_BC_DISHS_BC_DISHS2`
    FOREIGN KEY (`DISH_ID` )
    REFERENCES `bocai`.`BC_DISH` (`POST_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `bocai`.`BC_XREF_USER_VIEW_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_XREF_USER_VIEW_HISTORY` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_XREF_USER_VIEW_HISTORY` (
  `USER_ID` BIGINT NOT NULL ,
  `DISH_ID` BIGINT NOT NULL ,
  PRIMARY KEY (`USER_ID`, `DISH_ID`) ,
  INDEX `FK_BC_USER_HAS_BC_DISH_BC_DISH1` (`DISH_ID` ASC) ,
  INDEX `FK_BC_USER_HAS_BC_DISH_BC_USER1` (`USER_ID` ASC) ,
  CONSTRAINT `FK_BC_USER_HAS_BC_DISH_BC_USER1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BC_USER_HAS_BC_DISH_BC_DISH1`
    FOREIGN KEY (`DISH_ID` )
    REFERENCES `bocai`.`BC_DISH` (`POST_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `bocai`.`TASTE_PREFERENCES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`TASTE_PREFERENCES` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`TASTE_PREFERENCES` (
  `USER_ID` BIGINT NOT NULL ,
  `ITEM_ID` BIGINT NOT NULL ,
  `PREFERENCE` FLOAT NOT NULL ,
  PRIMARY KEY (`USER_ID`, `ITEM_ID`) ,
  INDEX `FK_BC_USER_HAS_BC_DISH_BC_DISH2` (`ITEM_ID` ASC) ,
  INDEX `FK_BC_USER_HAS_BC_DISH_BC_USER2` (`USER_ID` ASC) ,
  CONSTRAINT `FK_BC_USER_HAS_BC_DISH_BC_USER2`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BC_USER_HAS_BC_DISH_BC_DISH2`
    FOREIGN KEY (`ITEM_ID` )
    REFERENCES `bocai`.`BC_DISH` (`POST_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `bocai`.`BC_XREF_USER_DISH_RECOMMEND`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_XREF_USER_DISH_RECOMMEND` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_XREF_USER_DISH_RECOMMEND` (
  `USER_ID` BIGINT NOT NULL ,
  `DISH_ID` BIGINT NOT NULL ,
  PRIMARY KEY (`USER_ID`, `DISH_ID`) ,
  INDEX `FK_BC_USER_HAS_BC_DISH_BC_DISH3` (`DISH_ID` ASC) ,
  INDEX `FK_BC_USER_HAS_BC_DISH_BC_USER3` (`USER_ID` ASC) ,
  CONSTRAINT `FK_BC_USER_HAS_BC_DISH_BC_USER3`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BC_USER_HAS_BC_DISH_BC_DISH3`
    FOREIGN KEY (`DISH_ID` )
    REFERENCES `bocai`.`BC_DISH` (`POST_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `bocai`.`BC_USER_ACTIVITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bocai`.`BC_USER_ACTIVITIES` ;

CREATE  TABLE IF NOT EXISTS `bocai`.`BC_USER_ACTIVITIES` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `USER_ID` BIGINT NOT NULL ,
  `OBJECT` VARCHAR(45) NULL ,
  `OBJECTTYPE` VARCHAR(45) NULL ,
  `CONTENT` VARCHAR(200) NULL ,
  `OCCURS_TIME` VARCHAR(45) NULL ,
  `STATUS` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_BC_USER_ACTIVITIES_BC_USER1` (`USER_ID` ASC) ,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) ,
  CONSTRAINT `FK_BC_USER_ACTIVITIES_BC_USER1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `bocai`.`BC_USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
